name: example documents compilation tests

on:
  push:
    branches: [ master ]

jobs:
  tests:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - run: ls -al
      - run: sudo apt update
      - run: sudo apt install texlive-latex-recommended
      - run: echo '\shipout\hbox{}\end' | pdftex
      - run: cp texput.pdf example/tuda_logo.pdf
      - run: ./addlicense.sh
      - run: sed -i 's/points=true/points=false/g' example/DEMO-TUDaExercise.tex
      - run: cat example/DEMO-TUDaExercise.tex | grep points
      - run: sudo apt install texlive-latex-extra texlive-fonts-extra texlive-lang-cyrillic texlive-lang-german
      - run: pdflatex --version
      - run: cp tex/* example/
      - run: |
          cd example/
          ls -al
          echo ""
          pdflatex DEMO-TUDaExercise.tex
          echo ""
          ls -al | grep Exercise
