name: example documents compilation tests

on:
  push:
    branches: [ master ]

jobs:
  tests:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - run: ls -al
      - name: Install TeXLive from Ubuntu package sources
        run: |
          sudo apt update
          sudo apt install texlive-latex-recommended
      - name: Create logo file
        run: |
          echo '\shipout\hbox{}\end' | pdftex
          cp texput.pdf example/tuda_logo.pdf
      - name: Prepare the TUDa-CI template and install it
        run: |
          ./addlicense.sh
          cp tex/* example/
      - name: Do preparations specific for compilation with TeXLive 2019
        run: |
          sed -i 's/points=true/points=false/g' example/DEMO-TUDaExercise.tex
          cat example/DEMO-TUDaExercise.tex | grep points
      - name: Install additional TeX packages from the Ubuntu package sources
        run: sudo apt install texlive-latex-extra texlive-fonts-extra texlive-lang-cyrillic texlive-lang-german texlive-bibtex-extra
      - name: Get pdfLaTeX version
        run: pdflatex --version
      - name: Test if example exercise TeX file can be compiled
        run: |
          cd example/
          ls -al
          echo ""
          pdflatex DEMO-TUDaExercise.tex
          echo ""
          ls -al | grep Exercise
