name: example documents compilation tests

on:
  push:
    branches: [ master ]

jobs:
  tests:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - run: ls -al
      # - run: sudo apt update
      # - run: sudo apt install texlive-latex-recommended texlive-fonts-extra texlive-lang-cyrillic
      # - run: pdflatex --version
